### ISSUE TITLE
Integration of binary to decimal converter with decimal point

### ISSUE THREAD

**Issue by evilenx** [kentlouisetonino/baseshift#11]
![image](https://github.com/kentlouisetonino/baseshift/assets/111256110/d19af467-5785-47d4-86bc-4120bcb66b8b)

The current binary to decimal converter only works with integer binary numbers and cannot handle binary numbers with a decimal point. This limits the functionality of the converter and can cause problems for users who need to convert binary numbers with a decimal point to decimal.

**Suggestion:** 
Allow users to convert any binary number to decimal, regardless of whether it has a decimal point. Additionally, it is recommended to thoroughly test the converter to ensure that it works properly and provides accurate results.

**Comment by kentlouisetonino** [comment]
I will be migrating this project to C language. The bug fix
for this will be included here.

https://github.com/kentlouisetonino/baseshift/issues/13
